package Calendar::Model::Calendar;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Calendar::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:calendar',
        user => 'root',
        password => '',
        AutoCommit => q{1},
        on_connect_do => ["SET NAMES utf8"],
    }
);

=head1 NAME

Calendar::Model::Calendar - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Calendar>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Calendar::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

中森 創太

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
